FORMAT: 1A
HOST: https://www.delijn.be/

# De Lijn — Rise API
De Lijn Rise Web API, bekijk ook zeker eens de bijhorende blog post:
http://demey.io/reverse-engineering-belgium-de-lijn/

# Group Routeplanner
## Routeplanner [/rise-api-core/reisadvies/routes/{startPoint}/{endPoint}/{startX}/{startY}/{endX}/{endY}/{date}/{time}/{arrivalDeparture}/{byBus}/{byTram}/{byMetro}/{byTrain}/{byBelbus}/{language}]

Een beetje uitleg bij de verschillende parameters:

- `startPoint` en `endPoint` worden puur visueel gebruikt en hebben geen invloed op het reisadvies
- `datum` moet voldoen aan het volgende formaat: `dd-MM-yyyy`
- `tijd` moet voldoen aan het volgende formaat: `HH:mm`
- `arrivalDeparture` bepaald of je wilt aankomen of vertrekken op de gespecifieerde datum en tijd <br>
<table>
    <tr>
        <th>Option</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Vertrekken</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Aankomen</td>
    </tr>
</table>
- `byBus`, `byTram`, `byMetro`, `byTrain` and `byBelbus` parameters specifieren of je de die reismethoden wilt gebruiken
<table>
    <tr>
        <th>Option</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>on</td>
        <td>Aan</td>
    </tr>
    <tr>
        <td>of</td>
        <td>Af</td>
    </tr>
</table>

### GET
+ Parameters
    + startPoint (required, string, `Sint-Niklaas`) ... Beginpunt van de reis.
    + endPoint   (required, string, `Elversele, Temse`) ... Eindpunt van de reis.
    + startX     (required, number, `134103`) ... X coordinaat van het beginpunt.
    + startY     (required, number, `206073`) ... Y coordinaat van het beginpunt.
    + endX       (required, number, `133774`) ... X coordinaat van het eindpunt.
    + endY       (required, number, `200500`) ... Y coordinaat van het eindpunt.
    + date       (required, string, `04-07-2015`) ... Datum van het vertrek/aankomen.
    + time       (required, string, `20:00`) ... Tijd van het vertrek/aankomen.
    + arrivalDeparture (required, number, `1`) ... Vertrekken of aankomen modus.
    + byBus      (required, string, `on`) ... Zoek ook naar bus routes.
    + byTram     (required, string, `on`) ... Zoek ook naar tram routes.
    + byMetro    (required, string, `on`) ... Zoek ook naar metro routes.
    + byTrain    (required, string, `on`) ... Zoek ook naar trein routes.
    + byBelbus   (required, string, `of`) ... Zoek ook naar belbus routes.
    + language   (required, string, `nl`) ... De taal waarin je de resultaten wenst.

+ Response 200 (application/json)

# Group Haltes
Ophalen van haltes data

## In de buurt [/rise-api-core/haltes/indebuurt/{x_coordinaat}/{y_coordinaat}/{radius}]

### GET
+ Parameters
    + x_coordinaat (required, number, `103787`) ... X coordinaat
    + y_coordinaat (required, number, `194286`) ... Y coordinaat
    + radius (required, number, `300`) ... Zoek radius, eenheid onbekend

+ Response 200 (application/json)

## Informatie [/rise-api-core/haltes/titel/{halte_id}]

### GET
+ Parameters
    + halte_id (required, number, `200144`) ... Halte ID

+ Response 200 (application/json)

## Vertrekken [/rise-api-core/haltes/vertrekken/{halte_id}/{num_results}]

### GET
+ Parameters
    + num_results (optional, number, `5`) ... Maximum aantal resultaten
    + halte_id (required, number, `200144`) ... Halte ID

+ Response 200 (application/json)

## Doorkomende lijnen [/rise-api-core/haltes/doorkomendelijnen/{halte_id}]

### GET
+ Parameters
    + halte_id (required, number, `200144`) ... Halte ID

+ Response 200 (application/json)

# Group Lijnen

## Lijn informatie [/rise-api-core/lijnen/titel/{entiteit_nummer}/{lijnnummer_intern}/{richtingcode}]

### GET
+ Parameters
    + entiteit_nummer   (required, number, `2`)
    + lijnnummer_intern (required, number, `10`)
    + richtingcode      (required, number, `7`)

+ Response 200 (application/json)

## Halteregeling [/rise-api-core/dienstregeling/halteVolgorde/{entiteit_nummer}/{lijnnummer_intern}/{richtingcode}/{language}]

### GET
+ Parameters
    + entiteit_nummer   (required, number, `2`)
    + lijnnummer_intern (required, number, `292`)
    + richtingcode      (required, number, `7`)
    + language          (required, string, `nl`)

+ Response 200 (application/json)

## Dienstregeling [/rise-api-core/dienstregeling/dienstregeling/{entiteit_nummer}/{lijnnummer_intern}/{richtingcode}/{date}/{alle_haltes}/{language}]

### GET
+ Parameters
    + entiteit_nummer   (required, number, `2`)
    + lijnnummer_intern (required, number, `10`)
    + richtingcode      (required, number, `7`)
    + date              (required, string, `04-07-2015`)
    + alle_haltes       (required, boolean, `true`) ... Zet op `false` om enkel hoofdhaltes te tonen
    + language          (required, string, `nl`)

+ Response 200 (application/json)

## Omleidingen [/rise-api-core/reizigersberichten/omleidingen/lijn/{entiteit_nummer}/{lijnnummer_intern}/{richtingcode}/{date}/{language}]

### GET
+ Parameters
    + entiteit_nummer   (required, number, `2`)
    + lijnnummer_intern (required, number, `10`)
    + richtingcode      (required, number, `7`)
    + date              (required, string, `04-07-2015`)
    + language          (required, string, `nl`)

+ Response 200 (application/json)

# Group Gemeenten

## Gemeente Nieuws [/rise-api-search/search/gemeenteNieuws/{gemeente_id}/{page}/{num_results}]

### GET
+ Parameters
    + gemeente_id (required, string, `tcm:3-478-1024`)
    + page (required, string, `1`) ... Paginatie nummer
    + num_results (optional, number, `3`) ... Maximum aantal resultaten

+ Response 200 (application/json)

## Lijnen [/rise-api-core/lijnen/gemeente/{gemeente_id}]

### GET
+ Parameters
    + gemeente_id (required, number, `342`)

+ Response 200 (application/json)

# Group Locaties

## Verkoop gemeente zoeken [/rise-api-core/locations/verkoopGemeentes/{query}]

### GET
+ Parameters
    + query (required, string, `Gent`) ... Gemeente naam

+ Response 200 (application/json)

## Verkooppunten [/rise-api-core/locations/verkooppunten/{gemeente}]

### GET
+ Parameters
    + gemeente (required, string, `Gent`) ... Gemeente naam

+ Response 200 (application/json)

# Group Zoeken

## Search [/rise-api-search/search/search/{query}/{publication_id}]

### GET
+ Parameters
    + query (required, string, `Gent`) ... Zoek query
    + publication_id (required, number, `3`) ... Onbekend, injected in pagina

+ Response 200 (application/json)

## Quick Search [/rise-api-search/search/quicksearch/{query}]

### GET
+ Parameters
    + query (required, string, `brussel`) ... Zoek query

+ Response 200 (application/json)

## Gemeenten [/rise-api-search/search/quicksearch/gemeenten/{query}]

### GET
+ Parameters
    + query (required, string, `brussel`) ... Zoek query

+ Response 200 (application/json)

## Haltes [/rise-api-search/search/haltes/{query}/1]

### GET
+ Parameters
    + query (required, string, `gent-sint-pieters`) ... Zoek query

+ Response 200 (application/json)

## Locaties [/rise-api-search/locations/locatiezoeker/{num_results}/{query}]

### GET
+ Parameters
    + num_results (optional, number, `5`) ... Maximum aantal resultaten
    + query (required, string, `gent-sint-pieters`) ... Zoek query

+ Response 200 (application/json)

## Infopagina's [/rise-api-search/search/infopaginas/{query}/1/{publication_id}]

### GET
+ Parameters
    + query (required, string, `brussel`) ... Zoek query
    + publication_id (required, number, `3`) ... Onbekend, injected in pagina

+ Response 200 (application/json)

## Nieuws [/rise-api-search/search/nieuwsoverzicht/{category_id}/{language_id}/{page}]

### GET
+ Parameters
    + category_id (required, string, `tcm:3-428-1024`)
    + language_id (required, number, `3`) ... Taal ID
    + page (required, number, `1`) ... Paginatie nummer

+ Response 200 (application/json)
